/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Faq = {
  _type: "faq";
  items: Array<{
    question: string;
    answer: string;
    _type: "qa";
    _key: string;
  }>;
};

export type ContentTable = {
  _type: "contentTable";
  hasHeader?: boolean;
  rows: Array<{
    cells?: Array<string>;
    _type: "row";
    _key: string;
  }>;
};

export type CodeBlock = {
  _type: "codeBlock";
  language?:
    | "text"
    | "bash"
    | "json"
    | "javascript"
    | "typescript"
    | "tsx"
    | "html"
    | "css"
    | "sql";
  filename?: string;
  code: string;
};

export type Callout = {
  _type: "callout";
  tone?: "info" | "success" | "warn";
  title?: string;
  body: string;
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            reference?: PostReference;
            _type: "internalLink";
            _key: string;
          }
        | {
            href: string;
            _type: "link";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      fullBleed?: boolean;
      _type: "figure";
      _key: string;
    }
  | ({
      _key: string;
    } & Callout)
  | ({
      _key: string;
    } & CodeBlock)
  | ({
      _key: string;
    } & ContentTable)
  | ({
      _key: string;
    } & Faq)
>;

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
  };
  body: BlockContent;
  faqs?: Array<{
    question: string;
    answer: string;
    _type: "qa";
    _key: string;
  }>;
  author: AuthorReference;
  categories: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  publishedAt: string;
  featured?: boolean;
  relatedManual?: Array<
    {
      _key: string;
    } & PostReference
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role?: string;
  bio?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | Faq
  | ContentTable
  | CodeBlock
  | Callout
  | PostReference
  | BlockContent
  | Tag
  | Slug
  | Category
  | AuthorReference
  | CategoryReference
  | TagReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/blog/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current) && publishedAt <= now()].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string>;

// Source: lib/blog/queries.ts
// Variable: POST_LIST_QUERY
// Query: *[_type == "post" && defined(slug.current) && publishedAt <= now()] | order(publishedAt desc) {  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  "featured": coalesce(featured, false),  "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,  "coverImage": coverImage{    _type, asset, hotspot, crop, alt, caption,    "lqip": asset->metadata.lqip,    "aspectRatio": asset->metadata.dimensions.aspectRatio  },  "author": author->{ name, "slug": slug.current },  "categories": categories[]->{ title, "slug": slug.current },  "tags": tags[]->{ title, "slug": slug.current }}
export type POST_LIST_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  featured: boolean | false;
  readingTime: number;
  coverImage: {
    _type: "image";
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
    caption: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  };
  author: {
    name: string;
    slug: string;
  };
  categories: Array<{
    title: string;
    slug: string;
  }>;
  tags: Array<{
    title: string;
    slug: string;
  }> | null;
}>;

// Source: lib/blog/queries.ts
// Variable: FEATURED_POST_QUERY
// Query: *[_type == "post" && defined(slug.current) && publishedAt <= now() && featured == true] | order(publishedAt desc)[0] {  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  "featured": coalesce(featured, false),  "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,  "coverImage": coverImage{    _type, asset, hotspot, crop, alt, caption,    "lqip": asset->metadata.lqip,    "aspectRatio": asset->metadata.dimensions.aspectRatio  },  "author": author->{ name, "slug": slug.current },  "categories": categories[]->{ title, "slug": slug.current },  "tags": tags[]->{ title, "slug": slug.current }}
export type FEATURED_POST_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  featured: boolean | false;
  readingTime: number;
  coverImage: {
    _type: "image";
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
    caption: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  };
  author: {
    name: string;
    slug: string;
  };
  categories: Array<{
    title: string;
    slug: string;
  }>;
  tags: Array<{
    title: string;
    slug: string;
  }> | null;
} | null;

// Source: lib/blog/queries.ts
// Variable: POSTS_BY_CATEGORY_QUERY
// Query: *[_type == "post" && defined(slug.current) && publishedAt <= now() && $slug in categories[]->slug.current] | order(publishedAt desc) {  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  "featured": coalesce(featured, false),  "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,  "coverImage": coverImage{    _type, asset, hotspot, crop, alt, caption,    "lqip": asset->metadata.lqip,    "aspectRatio": asset->metadata.dimensions.aspectRatio  },  "author": author->{ name, "slug": slug.current },  "categories": categories[]->{ title, "slug": slug.current },  "tags": tags[]->{ title, "slug": slug.current }}
export type POSTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  featured: boolean | false;
  readingTime: number;
  coverImage: {
    _type: "image";
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
    caption: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  };
  author: {
    name: string;
    slug: string;
  };
  categories: Array<{
    title: string;
    slug: string;
  }>;
  tags: Array<{
    title: string;
    slug: string;
  }> | null;
}>;

// Source: lib/blog/queries.ts
// Variable: POSTS_BY_TAG_QUERY
// Query: *[_type == "post" && defined(slug.current) && publishedAt <= now() && $slug in tags[]->slug.current] | order(publishedAt desc) {  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  "featured": coalesce(featured, false),  "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,  "coverImage": coverImage{    _type, asset, hotspot, crop, alt, caption,    "lqip": asset->metadata.lqip,    "aspectRatio": asset->metadata.dimensions.aspectRatio  },  "author": author->{ name, "slug": slug.current },  "categories": categories[]->{ title, "slug": slug.current },  "tags": tags[]->{ title, "slug": slug.current }}
export type POSTS_BY_TAG_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  featured: boolean | false;
  readingTime: number;
  coverImage: {
    _type: "image";
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
    caption: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  };
  author: {
    name: string;
    slug: string;
  };
  categories: Array<{
    title: string;
    slug: string;
  }>;
  tags: Array<{
    title: string;
    slug: string;
  }> | null;
}>;

// Source: lib/blog/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    "updatedAt": _updatedAt,    "featured": coalesce(featured, false),    "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,    "coverImage": coverImage{      _type, asset, hotspot, crop, alt, caption,      "lqip": asset->metadata.lqip,      "aspectRatio": asset->metadata.dimensions.aspectRatio    },    body,    faqs,    "author": author->{ name, "slug": slug.current, role, bio, avatar },    "categories": categories[]->{ title, "slug": slug.current },    "tags": tags[]->{ title, "slug": slug.current },    seo,    "relatedManual": relatedManual[]->{      _id, title, "slug": slug.current, excerpt, publishedAt,      "featured": coalesce(featured, false),      "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,      "coverImage": coverImage{        _type, asset, hotspot, crop, alt, caption,        "lqip": asset->metadata.lqip,        "aspectRatio": asset->metadata.dimensions.aspectRatio      },      "author": author->{ name, "slug": slug.current },      "categories": categories[]->{ title, "slug": slug.current },      "tags": tags[]->{ title, "slug": slug.current }    }  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  updatedAt: string;
  featured: boolean | false;
  readingTime: number;
  coverImage: {
    _type: "image";
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
    caption: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  };
  body: BlockContent;
  faqs: Array<{
    question: string;
    answer: string;
    _type: "qa";
    _key: string;
  }> | null;
  author: {
    name: string;
    slug: string;
    role: string | null;
    bio: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  };
  categories: Array<{
    title: string;
    slug: string;
  }>;
  tags: Array<{
    title: string;
    slug: string;
  }> | null;
  seo: Seo | null;
  relatedManual: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    featured: boolean | false;
    readingTime: number;
    coverImage: {
      _type: "image";
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
      caption: string | null;
      lqip: string | null;
      aspectRatio: number | null;
    };
    author: {
      name: string;
      slug: string;
    };
    categories: Array<{
      title: string;
      slug: string;
    }>;
    tags: Array<{
      title: string;
      slug: string;
    }> | null;
  }> | null;
} | null;

// Source: lib/blog/queries.ts
// Variable: RELATED_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current) && publishedAt <= now() && slug.current != $slug &&     (count((categories[]->slug.current)[@ in $categories]) > 0 ||      count((tags[]->slug.current)[@ in $tags]) > 0)]    | order(publishedAt desc)[0...6] {  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  "featured": coalesce(featured, false),  "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,  "coverImage": coverImage{    _type, asset, hotspot, crop, alt, caption,    "lqip": asset->metadata.lqip,    "aspectRatio": asset->metadata.dimensions.aspectRatio  },  "author": author->{ name, "slug": slug.current },  "categories": categories[]->{ title, "slug": slug.current },  "tags": tags[]->{ title, "slug": slug.current }}
export type RELATED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  featured: boolean | false;
  readingTime: number;
  coverImage: {
    _type: "image";
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
    caption: string | null;
    lqip: string | null;
    aspectRatio: number | null;
  };
  author: {
    name: string;
    slug: string;
  };
  categories: Array<{
    title: string;
    slug: string;
  }>;
  tags: Array<{
    title: string;
    slug: string;
  }> | null;
}>;

// Source: lib/blog/queries.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc){ title, "slug": slug.current, description }
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  title: string;
  slug: string;
  description: string | null;
}>;

// Source: lib/blog/queries.ts
// Variable: ALL_TAGS_QUERY
// Query: *[_type == "tag"] | order(title asc){ title, "slug": slug.current }
export type ALL_TAGS_QUERY_RESULT = Array<{
  title: string;
  slug: string;
}>;

// Source: lib/blog/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{ title, "slug": slug.current, description }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  title: string;
  slug: string;
  description: string | null;
} | null;

// Source: lib/blog/queries.ts
// Variable: TAG_BY_SLUG_QUERY
// Query: *[_type == "tag" && slug.current == $slug][0]{ title, "slug": slug.current }
export type TAG_BY_SLUG_QUERY_RESULT = {
  title: string;
  slug: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post" && defined(slug.current) && publishedAt <= now()].slug.current': POST_SLUGS_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current) && publishedAt <= now()] | order(publishedAt desc) {\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  "featured": coalesce(featured, false),\n  "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,\n  "coverImage": coverImage{\n    _type, asset, hotspot, crop, alt, caption,\n    "lqip": asset->metadata.lqip,\n    "aspectRatio": asset->metadata.dimensions.aspectRatio\n  },\n  "author": author->{ name, "slug": slug.current },\n  "categories": categories[]->{ title, "slug": slug.current },\n  "tags": tags[]->{ title, "slug": slug.current }\n}': POST_LIST_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current) && publishedAt <= now() && featured == true] | order(publishedAt desc)[0] {\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  "featured": coalesce(featured, false),\n  "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,\n  "coverImage": coverImage{\n    _type, asset, hotspot, crop, alt, caption,\n    "lqip": asset->metadata.lqip,\n    "aspectRatio": asset->metadata.dimensions.aspectRatio\n  },\n  "author": author->{ name, "slug": slug.current },\n  "categories": categories[]->{ title, "slug": slug.current },\n  "tags": tags[]->{ title, "slug": slug.current }\n}': FEATURED_POST_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current) && publishedAt <= now() && $slug in categories[]->slug.current] | order(publishedAt desc) {\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  "featured": coalesce(featured, false),\n  "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,\n  "coverImage": coverImage{\n    _type, asset, hotspot, crop, alt, caption,\n    "lqip": asset->metadata.lqip,\n    "aspectRatio": asset->metadata.dimensions.aspectRatio\n  },\n  "author": author->{ name, "slug": slug.current },\n  "categories": categories[]->{ title, "slug": slug.current },\n  "tags": tags[]->{ title, "slug": slug.current }\n}': POSTS_BY_CATEGORY_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current) && publishedAt <= now() && $slug in tags[]->slug.current] | order(publishedAt desc) {\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  "featured": coalesce(featured, false),\n  "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,\n  "coverImage": coverImage{\n    _type, asset, hotspot, crop, alt, caption,\n    "lqip": asset->metadata.lqip,\n    "aspectRatio": asset->metadata.dimensions.aspectRatio\n  },\n  "author": author->{ name, "slug": slug.current },\n  "categories": categories[]->{ title, "slug": slug.current },\n  "tags": tags[]->{ title, "slug": slug.current }\n}': POSTS_BY_TAG_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    "updatedAt": _updatedAt,\n    "featured": coalesce(featured, false),\n    "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,\n    "coverImage": coverImage{\n      _type, asset, hotspot, crop, alt, caption,\n      "lqip": asset->metadata.lqip,\n      "aspectRatio": asset->metadata.dimensions.aspectRatio\n    },\n    body,\n    faqs,\n    "author": author->{ name, "slug": slug.current, role, bio, avatar },\n    "categories": categories[]->{ title, "slug": slug.current },\n    "tags": tags[]->{ title, "slug": slug.current },\n    seo,\n    "relatedManual": relatedManual[]->{\n      _id, title, "slug": slug.current, excerpt, publishedAt,\n      "featured": coalesce(featured, false),\n      "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,\n      "coverImage": coverImage{\n        _type, asset, hotspot, crop, alt, caption,\n        "lqip": asset->metadata.lqip,\n        "aspectRatio": asset->metadata.dimensions.aspectRatio\n      },\n      "author": author->{ name, "slug": slug.current },\n      "categories": categories[]->{ title, "slug": slug.current },\n      "tags": tags[]->{ title, "slug": slug.current }\n    }\n  }': POST_BY_SLUG_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current) && publishedAt <= now() && slug.current != $slug &&\n     (count((categories[]->slug.current)[@ in $categories]) > 0 ||\n      count((tags[]->slug.current)[@ in $tags]) > 0)]\n    | order(publishedAt desc)[0...6] {\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  "featured": coalesce(featured, false),\n  "readingTime": round(length(pt::text(body)) / 5 / 200) + 1,\n  "coverImage": coverImage{\n    _type, asset, hotspot, crop, alt, caption,\n    "lqip": asset->metadata.lqip,\n    "aspectRatio": asset->metadata.dimensions.aspectRatio\n  },\n  "author": author->{ name, "slug": slug.current },\n  "categories": categories[]->{ title, "slug": slug.current },\n  "tags": tags[]->{ title, "slug": slug.current }\n}': RELATED_POSTS_QUERY_RESULT;
    '*[_type == "category"] | order(title asc){ title, "slug": slug.current, description }': ALL_CATEGORIES_QUERY_RESULT;
    '*[_type == "tag"] | order(title asc){ title, "slug": slug.current }': ALL_TAGS_QUERY_RESULT;
    '*[_type == "category" && slug.current == $slug][0]{ title, "slug": slug.current, description }': CATEGORY_BY_SLUG_QUERY_RESULT;
    '*[_type == "tag" && slug.current == $slug][0]{ title, "slug": slug.current }': TAG_BY_SLUG_QUERY_RESULT;
  }
}
