/* ============================================================
   Inovacure — single-file HTML → Next.js extractor.
   Regenerates the DERIVED artifacts from the original prototype:
     - app/globals.css        (the <style> block)
     - public/assets/*        (inline base64 images, decoded to files)
     - public/engine.js       (the storefront engine, image URIs rewritten)
     - components/shellHtml.ts (the body markup, minus the engine script)
   The static scaffolding (layout/page/config) is hand-authored and
   NOT touched here, so re-running only refreshes content from source.
   Run:  npm run port
   ============================================================ */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const ORIGINAL = path.resolve(ROOT, '..', 'index (14).html');

const html = fs.readFileSync(ORIGINAL, 'utf8');

/* ---- slice the three regions ---- */
const styleStart = html.indexOf('<style>');
const styleEnd = html.indexOf('</style>');
if (styleStart < 0 || styleEnd < 0) throw new Error('Could not locate <style> block');
const css = html.slice(styleStart + '<style>'.length, styleEnd).trim();

// The engine is the only bare "<script>" (head scripts carry attributes).
const engineOpen = html.indexOf('<script>');
const engineClose = html.lastIndexOf('</script>');
if (engineOpen < 0 || engineClose < 0) throw new Error('Could not locate engine <script>');
let engine = html.slice(engineOpen + '<script>'.length, engineClose).trim();

const bodyOpen = html.indexOf('<body>');
let shell = html.slice(bodyOpen + '<body>'.length, engineOpen).trim();

/* ---- decode inline base64 images to files, rewrite URIs ---- */
const assetsDir = path.join(ROOT, 'public', 'assets');
fs.mkdirSync(assetsDir, { recursive: true });
// clear stale generated assets
for (const f of fs.readdirSync(assetsDir)) if (/^img-\d+\./.test(f)) fs.rmSync(path.join(assetsDir, f));

const extFor = (mime) => ({ 'svg+xml': 'svg', jpeg: 'jpg' }[mime] || mime);
const seen = new Map();
let n = 0, bytes = 0;
const rewrite = (str) => str.replace(
  /data:image\/([a-zA-Z0-9.+-]+);base64,([A-Za-z0-9+/=]+)/g,
  (m, mime, b64) => {
    if (seen.has(m)) return seen.get(m);
    n++;
    const file = `img-${n}.${extFor(mime)}`;
    const buf = Buffer.from(b64, 'base64');
    fs.writeFileSync(path.join(assetsDir, file), buf);
    bytes += buf.length;
    const p = `/assets/${file}`;
    seen.set(m, p);
    return p;
  }
);
engine = rewrite(engine);
shell = rewrite(shell); // in case any markup carried inline data URIs

/* ---- give the dynamic JSON-LD node a home inside the mounted markup ---- */
if (!shell.includes('id="pdpLd"')) {
  shell += '\n<script id="pdpLd" type="application/ld+json"></script>';
}

/* ---- write derived files ---- */
fs.mkdirSync(path.join(ROOT, 'app'), { recursive: true });
fs.mkdirSync(path.join(ROOT, 'public'), { recursive: true });
fs.mkdirSync(path.join(ROOT, 'components'), { recursive: true });

fs.writeFileSync(path.join(ROOT, 'app', 'globals.css'), css + '\n');
fs.writeFileSync(path.join(ROOT, 'public', 'engine.js'), "'use strict';\n" + engine.replace(/^'use strict';\s*/, '') + '\n');
fs.writeFileSync(
  path.join(ROOT, 'components', 'shellHtml.ts'),
  '/* AUTO-GENERATED by scripts/port.mjs — do not edit by hand. */\n' +
  'export const SHELL_HTML = ' + JSON.stringify(shell) + ';\n'
);

console.log(`✓ globals.css        ${(css.length / 1024).toFixed(1)} KB`);
console.log(`✓ public/engine.js   ${(engine.length / 1024).toFixed(1)} KB`);
console.log(`✓ components/shellHtml.ts (${(shell.length / 1024).toFixed(1)} KB markup)`);
console.log(`✓ ${n} image(s) → public/assets  (${(bytes / 1024).toFixed(0)} KB decoded)`);
